### ISSUE TITLE
Waiter causes plots to not be displayed in IE11

### ISSUE THREAD

**Issue by mcmcapewell** [JohnCoene/waiter#48] opened 2020-02-20 16:38 UTC
When running a Shiny app that contains `waiter::use_waiter()`, it won't render any R plot output (both ggplot and base R) when viewing in Internet Explorer 11. It works fine when viewing in Chrome, in a pop-out window or in the viewer in RStudio.

I'm using version 0.1.0 of `waiter` and 1.4.0 of `shiny`, and the problem persists in R and RStudio. The version of Internet Explorer is 11.973.17763.0.

Reprex below, taken from example "01_hello":

```
library(shiny)
library(waiter) 

ui <- fluidPage(
  waiter::use_waiter(), 
  
  titlePanel("Hello Shiny!"),

  sidebarLayout(
    
    sidebarPanel(
      
      sliderInput(inputId = "bins",
                  label = "Number of bins:",
                  min = 1,
                  max = 50,
                  value = 30)
      
    ),
    
    mainPanel(
      
      plotOutput(outputId = "distPlot")
      
    )
  )
)

server <- function(input, output) {

  output$distPlot <- renderPlot({
    
    x    <- faithful$waiting
    bins <- seq(min(x), max(x), length.out = input$bins + 1)
    
    hist(x, breaks = bins, col = "#75AADB", border = "white",
         xlab = "Waiting time to next eruption (in mins)",
         main = "Histogram of waiting times")
    
  })
  
}

# Create Shiny app ----
shinyApp(ui = ui, server = server)
```
Works fine in R windows, but the problem only occurs for Internet Explorer.

**Comment by JohnCoene** [comment] 2020-02-22 17:58
Hi,

Thank you for opening the issue. It's going to be difficult to debug given I have no windows, my test in Safari with Internet Explorer developer agents did not reveal any issue. Are you certain it is caused by `use_waiter`?

If so, would you mind sharing with me a print screen of the Internet Explorer console, which I assume would be displaying error messages?

Thank you.

**Comment by mcmcapewell** [comment] 2020-02-25 09:59
Hello,

I’m fairly sure it’s due to the package, since when I remove that one line, it functions properly. The code above is based on the `01_hello` Shiny example.

I’ve attached an image of the output below - it states “Object does not support property or method ‘includes’” in `waiter.js` (142, 3).

![07BFA918-98BC-4D52-944F-8189825DA56A](https://user-images.githubusercontent.com/61282014/75236227-66959e80-57b5-11ea-98e3-1b857459c640.png)

**Comment by JohnCoene** [comment] 2020-02-29 17:48
I just pushed a fix, it should work on Internet Explorer 11. Thank you for reporting this. Feel free to re-open if it still does not work.

**Closed by JohnCoene** 2020-02-29 17:48 UTC
Labels: IE11
