### ISSUE TITLE
display waiter when loading data asynchronously

### ISSUE THREAD

**Issue by gofford** [JohnCoene/waiter#58] opened 2020-08-03 13:18 UTC
Hey,

Great set of packages you've developed here!

I am trying to work with `waiter` to display a loading icon for a set of charts that take different lengths of time to load. I am loading the data asynchronously via a `reactiveValues` container, with the rendering deferred using `req()` statements. The method I am using is based on that outlined here: https://engineering-shiny.org/optimizing-shiny-code.html#asynchronous-in-shiny.

I can't seem to get the waiter to display (and stay displaying) in this scenario: it displays for a second and then disappears, with the chart rendering some seconds later. Is there a way to ensure that the loading icon persists until after the data are both loaded through the future _and_ the charts are rendered?

Here's an example, adapted from above:

```r
library(shiny)
library(promises)
library(future)
library(waiter)
plan(multisession)

ui <- function(request){
  tagList(
    use_waiter(),
    plotOutput("test"), 
    plotOutput("plot")
  )
}

server <- function(
  input, 
  output, 
  session
) {
  
  w_test <- Waiter$new(id = "test")
  w_plot <- Waiter$new(id = "plot")
  
  rv <- reactiveValues(
    res = NULL
  )
  
  w_test$show() #show by default.
  w_plot$show()
  
  future({
    Sys.sleep(5) # mimic long operation
    mtcars
  }) %...>%
    (function(e){ # on success assign value to reactiveValues
      rv$res <- e
    }) %...!%
    (function(e){ # otherwise return NULL
      rv$res <- NULL
      warning(e)
    })
  
  ## WORKS
  output$plot <- renderPlot({
    w_plot$hide()
    plot(iris)
  })
  
  ## DOES NOT WORK
  output$test <- renderPlot({
    req(rv$res)
    w_test$hide() # hide when data is loaded?
    plot(rv$res$mpg, rv$res$cyl)
  })
}

shinyApp(ui, server)
```

Unclear what I'm doing wrong here -- can you help?

**Comment by JohnCoene** [comment] 2020-08-05 10:53
I'm afraid you have stumbled upon a bug, sorry. I'll look into it.

**Comment by gofford** [comment] 2020-08-05 18:59
No worries @JohnCoene. I'd really like to use `waiter` to enhance the user experience of our tools, so looking forward to a fix! 

Really appreciate all of your effort on these packages. Some really high quality and great work here!

**Comment by JohnCoene** [comment] 2021-10-03 19:32
I know it's been a while but I'm gonna have to go ahead and close this. 

I've not forgotten, I've tried several things in the past as this is an issue I run into myself.
I'm afraid it cannot be fixed.

**Closed by JohnCoene** 2021-10-03 19:32 UTC
Labels: bug, enhancement, help wanted

**Comment by RoReke** [comment] 2022-12-06 15:31
Hi everyone, @IvanM26 and I were working on a similar issue and we found a solution. The idea is simple: you should not cancel the output by the `req()` function. Some conclusions from our research are:

R/Shiny async programming is not supposed to work intra-session [by design](https://github.com/rstudio/promises/issues/23#issuecomment-386687705) in reactive/observer expressions.

Renders are initiated as NULL. When the future() is resolved, the new value is going to trigger the render again. This is the trick.

For more documentation and examples on inner-session asynchronicity, see https://engineering-shiny.org/optimizing-shiny-code.html#b.-inner-session-asynchronicity.

```
library(shiny)
library(promises)
library(future)
library(waiter)
plan(multisession)

ui <- function(request){
  tagList(
    use_waiter(),
    plotOutput("test"), 
    plotOutput("plot")
  )
}

server <- function(
    input, 
    output, 
    session
) {
  
  w_test <- Waiter$new(id = "test")
  w_plot <- Waiter$new(id = "plot")
  
  rv <- reactiveValues(
    res = NULL
  )
  
  w_test$show() #show by default.
  w_plot$show()
  
  future({
    Sys.sleep(5) # mimic long operation
    mtcars
  }) %...>%
    (function(e){ # on success assign value to reactiveValues
      rv$res <- e
    }) %...!%
    (function(e){ # otherwise return NULL
      rv$res <- NULL
      warning(e)
    })
  
  ## WORKS
  output$plot <- renderPlot({
    w_plot$hide()
    plot(iris)
  })
  
  ## WORKS
  output$test <- renderPlot({
    req(rv$res, cancelOutput = TRUE)
    w_test$hide() # hide when data is loaded
    plot(rv$res$mpg, rv$res$cyl)
  })
}

shinyApp(ui, server)
```
